### ISSUE TITLE
[update] 能否考虑修改下vue-star-plus__decoration?

### ISSUE THREAD

**Issue by Moon1102** [savoygu/vue-star-plus#3]
其实可以理解vue-star-plus__decoration的宽高(可能)要100px的空间来正确的展示出动画，但是其定位为absoulte的情况下还不自适应icon的位置就有点难过了，如果用在那种回复点赞的情况图标要求占用空间很小，vue-star-plus__icon宽高变小了以后vue-star-plus__decoration就不会跟着走，依旧维持原来100x100的位置

大佬要不考虑下```.vue-star-plus__decoration{top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);}``` 来替代上下左右

**Comment by savoygu** [comment]
发布了 [3.2.0](https://github.com/savoygu/vue-star-plus/releases/tag/v3.2.0) ，可设置 props `type="center"`
